### PR TITLE
use tmp directory for saves

### PR DESCRIPTION
**Pull request by noskill**
closes issue #17

### CODE REVIEW

**Comment by DaddyWesker** [comment]
Well, I've met interesting behavior, don't know if it supposed to be like this.
1. I've removed all previously generated by Vereya worlds (only two left, they weren't created by Vereya)
2. Launched test_craft.py, stopped it, "save and quit".
3. World is in the list of worlds, but two worlds I've left are gone.
4. I've restarted the game and I'm seeing two worlds I've left and no vereya worlds. Everything fine? Well...
5. I've repeated 2-4 and here is what i've got

Worlds after repeated 2-3. As we can see, now there are two worlds created by Vereya and no other.


After restart I've seen no Vereya worlds 


But after launching and stopping script once again, I'm now see three vereya worlds. 


So, is this supposed to happen? I thought vereya worlds now should be deleted after game is closed, or not? Though, I've seen in your code that you've replaced folder containing vereya worlds. So, will they be deleted in this new tmp folder? And when?

**Comment by noskill** [comment]
@DaddyWesker with this PR minecraft is set to use temporary directory for saves. This way you can copy this saves to the default save directory if you want to.

**Comment by DaddyWesker** [comment]
> @DaddyWesker with this PR minecraft is set to use temporary directory for saves. This way you can copy this saves to the default save directory if you want to.

No, thing is not to save them, but to delete them, but they are persists in temp directory. Or they will be deleted after system reboot?

**Comment by noskill** [comment]
yes, temporary directory is temporary, so i decided it's ok to keep saves temporary

**Review by DaddyWesker — APPROVED** [review]

**Comment by noskill** [comment]
I am thinking maybe it is better to reset back saves directory. Current behaviour is too surprising.

**Comment by noskill** [comment]
@DaddyWesker now worlds created from scripts get saved in tmp directory, otherwise the behaviour should be the same as before this PR.

**Comment by DaddyWesker** [comment]
Ok, everything seems fine on my side.

**Pull request merged**
