### PR TITLE
continuous integration

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Review by DaddyWesker — COMMENTED** [review]
For some reason, this version of Vereya crashes test. What i mean - every second attempt to launch one of the test scripts it just fails to connect to the game. So, first launch everything goes fine. Second launch world is loading but then nothing happens and i can manipulate the agent with mouse and keyboard. Is this somehow related to the new addition in this particular PR or to noskill:ci branch not being fully updated?

**Comment by noskill** [comment]
@DaddyWesker there was a lot of bugs both in Vereya and in taglimo. Please check if the issue is still there. Tests passed successfully https://github.com/trueagi-io/Vereya/actions/runs/3794987272/jobs/6453637478

**Comment by DaddyWesker** [comment]
@noskill  the issue i mentioned is still persists. Even when i'm using your main branch of vereya with tagilmo.

**Review by CICS-Oleg — COMMENTED** [review]
I have a problem even with the first launch of mod in this branch. Neither test_craft test, nor scripts like achiever or explorer don't work. World is generated, mission starts, commands are sent, but the agent stands still. I'm now checking potential flaws on my side, but if someone has or had the same problems, please. tell.

**Comment by DaddyWesker** [comment]
Ok, latest commits fixed everything for me. 

@CICS-Oleg  try to pull latest commits and also check if you're using non-experimental tagilmo (get it from main branch of trueagi).

**Review by DaddyWesker — APPROVED** [review]

**Review by CICS-Oleg — APPROVED** [review]

**Pull request merged**
