### PR TITLE
don't use mod version for xml version

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Comment by DaddyWesker** [comment]
These changes broke test_observation.py in function test_observation_from_chat . self.rob.waitNotNoneObserve('getChat') now returning None as a result. Please check it, @noskill

**Comment by DaddyWesker** [comment]
And by the way, I'm still getting     ` control <?xml version="1.0" encoding="UTF-8"?><ping/>` when launching 6_achiever.py

**Comment by noskill** [comment]
>These changes broke test_observation.py

@DaddyWesker these changes didn't broke anything. Probably you are testing code from my branch https://github.com/noskill/Vereya/tree/xml_ve, which doesn't have all the recent changes

**Comment by noskill** [comment]
ping messages are not logged from Vereya mod btw, it can be fixed only on python side.

**Review by DaddyWesker — APPROVED** [review]

**Pull request merged**
