### PR TITLE
add minecraft version into json stats

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Comment by noskill** [comment]
mc.getFullStat('minecraft-version')

'fabric-loader-0.13.3-1.18.1'

**Comment by DaddyWesker** [comment]
I guess now we can get game version from within our vereya test? Maybe, we should update some of our tests to check if this works? I've tried this `res = mc.getFullStat('minecraft-version')` but it gives me `None`

**Comment by CICS-Oleg** [comment]
> but it gives me `None`

Same here.

**Review by CICS-Oleg — COMMENTED** [review]
Is it enough to call getFullStat('minecraft-version') from connctor in python script to get version? There is still None. Are you sure that MinecraftClient.getInstance().getGameVersion() gives the expected info? Can we check that?

**Comment by noskill** [comment]
@CICS-Oleg i moved version info to ping, since it is available even if world construction fails

**Review by CICS-Oleg — APPROVED** [review]

**Pull request merged**
