### PR TITLE
bugfix input change on setting screen

### PR DESCRIPTION
**Pull request by noskill**
should fix issue when input is set to human on mission start and when input is set to AI when title screen is open

### CODE REVIEW

**Comment by DaddyWesker** [comment]
That doesn't fixed 4_mine_and_craft.py for me. Can you check it on your side? Agent is still not moving while commands are being send to him. And only after I'm pressing Enter he starts to do something. That's not happening every time, but every second time for sure. At least for me.

**Comment by DaddyWesker** [comment]
Moreover, this PR somehow breaks 6_achiever so he doesn't know how to get diamond anymore. I've not changed anything else but lib from your pr. This is weird

**Comment by CICS-Oleg** [comment]
I've reproduced the problem with 4_mine_and_craft.py script. It not happens all the time, but still can be caught.

**Comment by CICS-Oleg** [comment]
Speaking about 6_achiever I haven't got diamond yet neither with old code versions, nor on the newest pr.

**Comment by DaddyWesker** [comment]
> Speaking about 6_achiever I haven't got diamond yet neither with old code versions, nor on the newest pr.

Well, problem not with getting diamond itself, but with (for some reason) error that throws achiever when i'm trying to type "get diamond". It just throws "panic, don't know how to obtain diamond". And that is weird. I've tried to see if info about diamond is in the minelogy and it's not. On the stage when we're getting info from the game it just doesn't give anything about diamond, iron_ore and copper_ore.

**Comment by noskill** [comment]
@DaddyWesker test for motion now works, could you please check the issue with 4_mine_and_craft.py ?

**Review by DaddyWesker — APPROVED** [review]

**Pull request merged**
