### PR TITLE
use lockfile during test

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Comment by DaddyWesker** [comment]
With this PR my fps dropped even further. @noskill  could you check it on your machine?

**Comment by noskill** [comment]
How can I do it? This pr doesn't modify source code of the mod.

**Comment by DaddyWesker** [comment]
Who knows. I'm just saying about results of my tests. If you can't check it on your machine - fine.

**Review by DaddyWesker — APPROVED** [review]

**Comment by noskill** [comment]
I didn't said i can't check. I can if you tell me how to do it.

**Comment by DaddyWesker** [comment]
Just launch achiever and check fps with and without this PR. Using F3. Though you probably will need to update this branch to master first.

**Comment by noskill** [comment]
What is the point of testing binary equal files? I unzipped jar file from this branch after merge, and from master branch and all files binary equal except one with timestamp.

**Comment by noskill** [comment]
version.properties contains timestamp, so each time you build a jar file it will be different due to zip compression

**Pull request merged**
