### PR TITLE
1.19.3

### PR DESCRIPTION
**Pull request by noskill**

### CODE REVIEW

**Comment by DaddyWesker** [comment]
I can't launch the game using provided launch.sh since i'm getting this. I've changed path to the game in launch.sh file and placed mods to the right place.

```
Listening for transport dt_socket at address: 8000
[08:46:10] [WARN] [FabricLoader/Knot]: Class path entries reference missing files: /home/leron/.minecraft/libraries/net/fabricmc/intermediary/1.19.3/intermediary-1.19.3.jar, /home/leron/.minecraft/versions/fabric-loader-0.14.11-1.19.3/fabric-loader-0.14.11-1.19.2.jar - the game may not load properly!
[08:46:10] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
[08:46:11] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:214)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by DaddyWesker** [comment]
I guess the problem is that i don't have this folder
`/home/leron/.minecraft/versions/fabric-loader-0.14.11-1.19.3`

Moreover, it seems that here `/home/leron/.minecraft/versions/fabric-loader-0.14.11-1.19.3/fabric-loader-0.14.11-1.19.2.jar` is the wrong .jar file (1.19.2). 

This line `--version fabric-loader-0.14.11-1.19.2` seems wrong too.

**Comment by DaddyWesker** [comment]
After new commits i'm getting this when trying to launch using your launch.sh
```
xvfb-run: error: Xvfb failed to start
process
```

**Comment by DaddyWesker** [comment]
So, i've tested with new commits and now i'm getting this

```
Listening for transport dt_socket at address: 8000
Error: Could not find or load main class net.fabricmc.loader.impl.launch.knot.KnotClient
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
process
```

**Review by Necr0x0Der — APPROVED** [review]

**Pull request merged**
