### PR TITLE
slightly better performance

### PR DESCRIPTION
**Pull request by DaddyWesker**
So, this change with change in [this PR](https://github.com/trueagi-io/minecraft-demo/pull/162) makes performance a little bit better.

### CODE REVIEW

**Review by Necr0x0Der — APPROVED** [review]

**Comment by noskill** [comment]
I added code that logs glReadPixes execution time averaged over 2000 frames ~ 2 minutes on my machine https://github.com/noskill/Vereya/tree/branch2 
Could you please run the code for a few minutes and give numbers for GL_BGRA vs GL_RGBA

i got BRGA 7.35 vs  7.2 RGBA

**Comment by DaddyWesker** [comment]
@noskill 
So, in your case, BGRA is slower? Weird. But thing is that this BGRA comes along with another change on the python side, where I removed RGB2BGR numpy conversion thanks to GL_BRGA.

**Comment by noskill** [comment]
@DaddyWesker no, it's faster, i misplaced the numbers, it should be  BRGA 7.2 vs  RGBA 7.35

**Comment by noskill** [comment]
There is large variation between successive 2000 frames, we need to average over larger timeframes.

**Comment by noskill** [comment]
@CICS-Oleg could you please also run the benchmark for a few minutes?

**Review by noskill — APPROVED** [review]

**Pull request merged**
